FROM php:7-apache

ARG VAULT_VERSION=1.5.4
ARG VAULT_ENVCONSUL_VERSION=0.10.0

RUN docker-php-ext-install mysqli
RUN apt-get update && apt-get install -y jq wget unzip curl tar

RUN wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip && unzip -d /bin vault_${VAULT_VERSION}_linux_amd64.zip
RUN curl -so envconsul.tgz https://releases.hashicorp.com/envconsul/${VAULT_ENVCONSUL_VERSION}/envconsul_${VAULT_ENVCONSUL_VERSION}_linux_amd64.tgz && tar -xvzf envconsul.tgz && mv envconsul /usr/local/bin/envconsul && chmod +x /usr/local/bin/envconsul

COPY vault/config.hcl /root/config.hcl
COPY vault/entrypoint.sh /usr/local/bin
